### ISSUE TITLE
Make the Resource Section

### ISSUE THREAD

**Issue by vashukashyap** [ElixirTechCommunity/learn-ups#10]
# what to do?
Design the Resource Section for the website and make sure it is Responsive.

## Reference Image
![Screenshot Capture - 2024-10-02 - 15-25-38](https://github.com/user-attachments/assets/20e7c365-0784-4965-b230-75e0049b94f8)

#### Make sure your PR is link to this issue.

**Comment by AashitaSharma** [comment]
Hello sir, I would like to contribute to this issue!

**Comment by vashukashyap** [comment]
@AashitaSharma Some issue is already assign to you make sure to complete them First.

**Comment by devina-agr** [comment]
Hello sir, I want to work on this issue!
