### ISSUE TITLE
Make the Footer

### ISSUE THREAD

**Issue by vashukashyap** [ElixirTechCommunity/learn-ups#11]
# What to do?
Design the footer  section of the website as shown in the " Reference Image " and add the community social link to the footer. 
links:
* discord link : https://discord.com/invite/YN9ZGjXdXK
* Github link: https://github.com/ElixirTechCommunity

## Reference Image
![Screenshot Capture - 2024-10-02 - 15-50-30](https://github.com/user-attachments/assets/7b6c8451-6c07-4df8-a446-16ed1acadd63)

#### Make sure the PR you do is link to this issue.

**Comment by Kinshu-Learner** [comment]
Hi! I would like to work on this issue.

**Comment by shivam8112005** [comment]
Hi, Assign me this issue.

**Comment by Akash-1808** [comment]
Hi, Please assign me this issue

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it I will make my best
