### ISSUE TITLE
Design a Jumboster

### ISSUE THREAD

**Issue by vashukashyap** [ElixirTechCommunity/learn-ups#6]
# What to do?
Design a jumboster for the website

## Reference image
![Screenshot Capture - 2024-10-02 - 14-48-30](https://github.com/user-attachments/assets/dc4d4c57-dbe2-4118-9edf-44ae2f5a26b1)

#### Make sure the PR you do is link to this issue.

**Comment by Abhay12911** [comment]
assign me this issue
