### ISSUE TITLE
Make The Title Section

### ISSUE THREAD

**Issue by vashukashyap** [ElixirTechCommunity/learn-ups#9]
# What to do?
Design the Section as specified in the " Reference Image " under the Recently Added section.

## Reference Image
![Screenshot Capture - 2024-10-02 - 15-21-56](https://github.com/user-attachments/assets/db7ed8f2-719f-41fd-8843-aa2bcf1a6276)

#### Make sure the PR you do is linked to this issue.

**Comment by soodshivansh** [comment]
Hi @vashukashyap I would like to work on this issue!

**Comment by Akash-1808** [comment]
hi  please assign me this issue
